style(aslant): set `react/require-extension` to off
error: « The react/require-extension rule is deprecated. Please use the
import/extensions rule from eslint-plugin-import instead. »

see:
https://github.com/airbnb/javascript/issues/978#issuecomment-244611697